# must be unique in a given SonarQube instance
sonar.projectKey=unir-test
sonar.sources=.
sonar.host.url=http://sonarqube-server:9000
# El token se pasa via variable de entorno SONAR_TOKEN al correr make start-sonar-scanner
sonar.coverage.exclusions=test/**/*,web/*
sonar.python.pylint.reportPath=results/pylint_result.txt
sonar.python.coverage.reportPaths=results/coverage.xml
sonar.python.xunit.reportPath=results/*_result.xml
